repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    # We can't use the latest version due to a regression in mypy 1.7.0
    # See https://github.com/python/mypy/issues/17191 for more information
    rev: v1.6.1
    hooks:
    - id: mypy
      additional_dependencies: [pytest, typing-extensions]
      types: [python]
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.362
    hooks:
    - id: pyright
      additional_dependencies: [pytest, typing-extensions]
      types: [python]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.272
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix]
